### ISSUE TITLE
NS ERROR FAILURE under Firefox

### ISSUE THREAD

**Issue by PascalNetenvie** [jehna/ga-lite#8] opened 2016-04-17 12:59 UTC
Hi,
Under chrome everything's fine but under Firefow we see this error :
Erreur : NS_ERROR_FAILURE: 
Fichier source : https://cdn.jsdelivr.net/ga-lite/latest/ga-lite.min.js
Ligne : 1

**Comment by jehna** [comment] 2016-04-18 06:17
Not seeing this error on Firefox, can you provide an example how to reproduce?

**Comment by PascalNetenvie** [comment] 2016-04-18 11:18
JS Console display that :

try{!function(a,b,c,d,e,f){a.addEventListener("load",function(){var g=(new Date).getTime();a.galite=a.galite||{};var h=new XMLHttpRequest,i="https://www.google-analytics.com/collect?cid="+(b.uid=b.uid||Math.random()+"."+Math.random())+"&v=1&tid="+galite.UA+"&dl="+f(location)+"&ul=en-us&de=UTF-8",j=function(a){var b="";for(var c in a){if(void 0===a[c])return!1;b+=f(a[c])}return b},k={dt:[e.title],sd:[d.colorDepth,"-bit"],sr:[d.availHeight,"x",d.availWidth],vp:[innerWidth,"x",innerHeight],dr:[e.referrer]};for(var l in k){var m=l+"="+j(k[l]);m&&(i+="&"+m)}var n=function(a){c.sendBeacon?c.sendBeacon(a):(h.open("GET",a,!1),h.send())},o=function(a,b){var c="";for(var d in b)c="&"+d+"="+f(b[d]);return function(){n(i+c+"&t="+f(a)+"&z="+(new Date).getTime())}};setTimeout(o("pageview"),100),a.addEventListener("unload",o("timing",{utc:"JS Dependencies",utv:"unload",utt:(new Date).getTime()-g}))})}(window,localStorage,navigator,screen,document,encodeURIComponent);}catch(e){console.error('Error in file:https://cdn.jsdelivr.net/ga-lite/latest/ga-lite.min.js; Error:'+e.message);};
try{var galite=galite||{};galite.UA='UA-2609739-1';}catch(e){console.error('Error in script declaration; Error:'+e.message);};
;

**Comment by PascalNetenvie** [comment] 2016-04-18 11:20
Site is here : http://www.netenvie.com/
Do you get the same in this site ?

**Comment by PascalNetenvie** [comment] 2016-04-18 11:26
Ok it don't come from optimizer.
This is Firefox return without, it's more clear :
L'utilisation d'XMLHttpRequest de façon synchrone sur le fil d'exécution principal est obsolète à cause de son impact négatif sur la navigation de l'utilisateur final. Consulter http://xhr.spec.whatwg.org/ pour plus d'informations.
In english :
Use of XMLHttpRequest in a sync way on the main execution process is obsolete because of its negative impact on final user browsing. See http://xhr.spec.whatwg.org/ for more informations.

**Comment by PascalNetenvie** [comment] 2016-04-18 11:27
I think you perhaps have an option for that on the CDN that host file ...

**Comment by jehna** [comment] 2016-04-18 15:30
@PascalNetenvie don't see the error on http://www.netenvie.com/

What browser + os version are you using? I'm on OSX with FF 45.0.2

**Comment by jehna** [comment] 2016-04-18 15:51
Also no error on Win7 / FF 45.0.2

**Comment by PascalNetenvie** [comment] 2016-04-18 16:24
Here Win7 / FF 45.0.2

**Comment by PascalNetenvie** [comment] 2016-04-18 16:44
Without extensions i still get it on this page :
http://www.netenvie.com/contact/form.html

On other it seems ok.

**Comment by jehna** [comment] 2016-04-18 17:29
I believe this was a cache problem? Try `ctrl`+`F5` on that page, it should clear the cache?

**Comment by PascalNetenvie** [comment] 2016-04-18 18:14
It change nothing ...

**Comment by jehna** [comment] 2016-04-18 18:16
That's strange. I still can't reproduce the problem, even on the contact form site.

**Comment by jehna** [comment] 2016-04-18 18:23
@PascalNetenvie were you able to pinpoint what caused the error on other pages?

**Comment by PascalNetenvie** [comment] 2016-04-18 18:27
No and to be true i remade tests and i still have problem on other pages too (even without extensions).
Always this message about XMLHttpRequest

**Comment by IrcDirk** [comment] 2016-05-05 10:45
Disable AdBlock! ;)

**Comment by PascalNetenvie** [comment] 2016-05-24 12:28
Hey i use uBlock.
Perhaps it is this but lot of people use adblockers so if it make the script bug then analytics data will be completly false ...

**Comment by jehna** [comment] 2016-05-24 16:31
@PascalNetenvie uBlock and other adblockers (among with browsers and and some antivirus software that have "do not track" functionalities) are meant to block tracking URLs like Google Analytics.

As privacy should be completely in the hands of users themselves, I fully agree that disabling all tracking should be easy for the end-user, as it currently is with the common tools.

Please note that this is not a bug with ga-lite, as you would be experiencing the same number of blocking with the official Google Analytics client. It is not the ga-lite library that's getting blocked, but the Google Analytics measurement protocol endpoint that it's using.

As a reference: I'm currently seeing anything from 10% to 50% of requests not being tracked to Google Analytics on my website projects, despite if I'm using the official GA client or ga-lite.

The workaround for this is to use the [Google Analytics measurement protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/) on your web server (e.g. with PHP), that sends all the requests performed to your web server directly to Google Analytics endpoint.

Note that if you use server-side tracking, you should comply with the [Google Analytics' policy](https://developers.google.com/analytics/devguides/collection/protocol/policy), especially with the clause about providing an easy opt-out possibility:

> ... You will either get consent from your end users, or provide them with the opportunity to opt-out from the implementations and features you use.

I'm closing this issue for now, as the library is working as it should.

**Closed by jehna** 2016-05-24 16:31 UTC
Labels: bug
