### ISSUE TITLE
Universal Analytics (GA3) and GA4 same time

### ISSUE THREAD

**Issue by nfn** [jehna/ga-lite#255] opened 2021-03-15 22:17 UTC
Hi

Can ga-lite be used for GA3 and GA4 at the same time (see bellow)?
Is the script able to log GA4?

Thanks

```<script>
(function(e,t,n,i,s,a,c){e[n]=e[n]||function(){(e[n].q=e[n].q||[]).push(arguments)}
;a=t.createElement(i);c=t.getElementsByTagName(i)[0];a.async=true;a.src=s
;c.parentNode.insertBefore(a,c)
})(window,document,"galite","script","https://cdn.jsdelivr.net/npm/ga-lite@2/dist/ga-lite.min.js");

galite('create', 'UA-XXXXXXXX-X', 'auto');
galite('create', 'G-XXXXXXXX', 'auto');
galite('send', 'pageview');
</script>```

**Comment by jehna** [comment] 2021-03-15 22:40
Unfortunately no. ga-lite uses the [measurement protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/) which only works for V3.
There is an [alpha API for the V4](https://developers.google.com/analytics/devguides/collection/protocol/ga4) that you could take a look. If it works similarly to the V3, then switching URLs to the new protocol should be straightforward.

If you're interested to take a look I'll be happy to accept pull requests!

**Comment by jehna** [comment] 2021-03-15 22:41
Closing as duplicate of #205

**Closed by jehna** 2021-03-15 22:41 UTC
