### ISSUE TITLE
GA-lite via RequireJS

### ISSUE THREAD

**Issue by philwareham** [jehna/ga-lite#20] opened 2017-07-03 09:08 UTC
Hi there, trying to get ga-lite running via [RequireJS](http://requirejs.org). Have this code in my main.js file (obviously `my-ua-account-no` is really my account number):

    require(['galite'], function()
    {
        var galite = galite || {};
        galite.UA = 'my-ua-account-no';
        galite.anonymizeIp = true;
    });

It seems when the request is made to `https://www.google-analytics.com/collect?` the `tid` value is `undefined`- any idea why this is happening?

**Comment by jehna** [comment] 2017-07-29 16:51
This is probably a duplicate of #22, closing this one

**Comment by philwareham** [comment] 2017-07-31 08:18
Sorry, I'm still getting this problem after upgrading to v1.1.2.

**Comment by jehna** [comment] 2017-12-05 17:10
@philwareham can you check if this bug still persists on 2.0.0? The new version was built from scratch, so the URL builder should now be more solid.

**Comment by jehna** [comment] 2018-01-25 18:39
Closing this issue for now, as it should not persist on 2.0.0 anymore. Please open a new issue if it still occurs.

**Closed by jehna** 2018-01-25 18:39 UTC
Labels: bug
